spring:
  application:
    name: housekeeping-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelos_housekeeping
    username: postgres
    password: "12345"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082
logging:
  level:
    com.hotelos: DEBUG
